# Generated by Django 5.2.6 on 2025-09-28 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=50, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('arsenic', models.FloatField(blank=True, null=True)),
                ('lead', models.FloatField(blank=True, null=True)),
                ('cadmium', models.FloatField(blank=True, null=True)),
                ('chromium', models.FloatField(blank=True, null=True)),
                ('collection_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComputedIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hpi_value', models.FloatField()),
                ('hei_value', models.FloatField(blank=True, null=True)),
                ('mi_value', models.FloatField(blank=True, null=True)),
                ('quality_category', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('poor', 'Poor'), ('very_poor', 'Very Poor')], max_length=20)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='computed_index', to='samples.watersample')),
            ],
        ),
    ]
