# Generated by Django 5.2.6 on 2025-09-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='computedindex',
            index=models.Index(fields=['calculation_year'], name='calculation_calcula_a9ef4b_idx'),
        ),
        migrations.AddIndex(
            model_name='computedindex',
            index=models.Index(fields=['location_name'], name='calculation_locatio_b721e4_idx'),
        ),
        migrations.AddIndex(
            model_name='computedindex',
            index=models.Index(fields=['quality_category'], name='calculation_quality_af8bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='computedindex',
            index=models.Index(fields=['hpi_value'], name='calculation_hpi_val_a21ae4_idx'),
        ),
        migrations.AddIndex(
            model_name='computedindex',
            index=models.Index(fields=['computed_at'], name='calculation_compute_c9dc5d_idx'),
        ),
        migrations.AddIndex(
            model_name='computedindex',
            index=models.Index(fields=['calculation_year', 'location_name'], name='calculation_calcula_c895ea_idx'),
        ),
        migrations.AddIndex(
            model_name='computedindex',
            index=models.Index(fields=['calculation_year', 'quality_category'], name='calculation_calcula_4447bc_idx'),
        ),
        migrations.AddIndex(
            model_name='computedindex',
            index=models.Index(fields=['state', 'district'], name='calculation_state_f90f6e_idx'),
        ),
    ]
