# Generated by Django 5.2.6 on 2025-09-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroundWaterSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField(unique=True, verbose_name='Serial Number')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('year', models.IntegerField()),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ec_us_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='EC (µS/cm)')),
                ('co3_mg_l', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='CO3 (mg/L)')),
                ('hco3_mg_l', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='HCO3 (mg/L)')),
                ('cl_mg_l', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Cl (mg/L)')),
                ('f_mg_l', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='F (mg/L)')),
                ('total_hardness_mg_l', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total Hardness (mg/L)')),
                ('fe_ppm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Fe (ppm)')),
                ('as_ppb', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='As (ppb)')),
                ('u_ppb', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='U (ppb)')),
            ],
            options={
                'verbose_name': 'Ground Water Sample',
                'verbose_name_plural': 'Ground Water Samples',
            },
        ),
    ]
