# Generated by Django 5.2.6 on 2025-09-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groundwatersample',
            name='ca_mg_l',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ca (mg/L)'),
        ),
        migrations.AddField(
            model_name='groundwatersample',
            name='k_mg_l',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='K (mg/L)'),
        ),
        migrations.AddField(
            model_name='groundwatersample',
            name='mg_mg_l',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Mg (mg/L)'),
        ),
        migrations.AddField(
            model_name='groundwatersample',
            name='na_mg_l',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Na (mg/L)'),
        ),
        migrations.AddField(
            model_name='groundwatersample',
            name='no3_mg_l',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='NO3 (mg/L)'),
        ),
        migrations.AddField(
            model_name='groundwatersample',
            name='po4_mg_l',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='PO4 (mg/L)'),
        ),
        migrations.AddField(
            model_name='groundwatersample',
            name='so4_mg_l',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='SO4 (mg/L)'),
        ),
    ]
