# Generated by Django 5.2.6 on 2025-09-30 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0002_groundwatersample_ca_mg_l_groundwatersample_k_mg_l_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groundwatersample',
            options={'ordering': ['s_no'], 'verbose_name': 'Ground Water Sample', 'verbose_name_plural': 'Ground Water Samples'},
        ),
        migrations.AddField(
            model_name='groundwatersample',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='groundwatersample',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='groundwatersample',
            name='district',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='groundwatersample',
            name='s_no',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='groundwatersample',
            name='state',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='groundwatersample',
            name='year',
            field=models.IntegerField(help_text='Year of sample collection', validators=[django.core.validators.MinValueValidator(1900)]),
        ),
    ]
